template_path: templates/jinja/generate_subnets.py
parameters:
  vpcCidr: !stack_output dev/network/vpc::VpcId
sceptre_user_data:
  Subnets:
    Cidrs:
      PrivateA: 12.0.1.0/24
      PrivateB: 12.0.2.0/24
      PublicA: 12.0.3.0/24
      PublicB: 12.0.4.0/24


  tags:
    Name: Giorgos' VPC
    Owner: giorgos.dimitriou
